server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Allow CORS for demo purposes
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
}
